version: "3"

services:
  ckan-dev:
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
    env_file:
      - .dev.env
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
      - ./src:/srv/app/src_extensions

  datapusher:
    container_name: datapusher
    image: keitaro/ckan-datapusher:0.0.17
    ports:
        - "8000:8000"
    environment:
        - DATAPUSHER_REWRITE_URL=http://ckan-dev:5000

  db:
    container_name: db
    env_file:
      - .dev.env
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    build:
      context: solr/

  redis:
    container_name: redis
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
