FROM openknowledge/ckan-dev:2.8

MAINTAINER Open Knowledge International <info@okfn.org>

# Install utilities
RUN pip install ipdb ipdbplugin

# Install any extensions needed by your CKAN instance
# (Make sure to add the plugins to CKAN__PLUGINS in the .env file)
# TODO: pin when possible
RUN echo 'Installing extensions' && \
    # scheming
    pip install -e git+https://github.com/ckan/ckanext-scheming.git#egg=ckanext-scheming && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-scheming/master/requirements.txt && \
    # harvest
    pip install -e git+https://github.com/ckan/ckanext-harvest.git@v1.1.4#egg=ckanext-harvest && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-harvest/v1.1.4/pip-requirements.txt && \
    # socrata harvester
    pip install -e git+https://github.com/okfn/ckanext-socrata.git@2.0.4a#egg=ckanext-socrata && \
    pip install -r https://raw.githubusercontent.com/okfn/ckanext-socrata/2.0.4a/requirements.txt && \
    # dcat harvester
    pip install -e git+https://github.com/ckan/ckanext-dcat.git@9d41e27b#egg=ckanext-dcat && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-dcat/v0.0.8/requirements.txt && \
    # googleanalytics
    pip install -e git+https://github.com/ckan/ckanext-googleanalytics.git#egg=ckanext-googleanalytics && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-googleanalytics/master/requirements.txt && \
    # disqus
    pip install -e git+https://github.com/ckan/ckanext-disqus#egg=ckanext-disqus && \
    # hierarchy
    pip install -e git+https://github.com/okfn/ckanext-hierarchy.git#egg=ckanext-hierarchy && \
    # showcase
    pip install -e git+https://github.com/okfn/ckanext-showcase.git#egg=ckanext-showcase && \
    # geoview
    pip install -e git+https://github.com/okfn/ckanext-geoview.git@#egg=ckanext-geoview && \
    # pdfview
    pip install -e git+https://github.com/okfn/ckanext-pdfview.git#egg=ckanext-pdfview  && \
    # contact
    pip install -e git+https://github.com/okfn/ckanext-contact.git@lacounts-0.1#egg=ckanext-contact

# Install project extension
RUN pip install -e git+https://github.com/okfn/ckanext-lacounts.git#egg=ckanext-lacounts

# Apply patches
COPY patches ${APP_DIR}/patches
RUN git config --global user.email "autopatcher@okfn.org" && \
    git config --global user.name "autopatcher" && \
    cd $SRC_DIR/ckan && \
    for f in $APP_DIR/patches/ckan/*; do echo "$0: Applying patch $f"; git apply "$f" ; done

# Copy config files
COPY crontabs/* /etc/crontabs/
COPY docker-entrypoint.d/* /docker-entrypoint.d/
COPY supervisor.d/* /etc/supervisord.d/
