FROM openknowledge/ckan-dev:2.8

MAINTAINER Viderum <info@Viderum.com>

# Install utilities
RUN pip install ipdb ipdbplugin python-gflags

# Install any extensions needed by your CKAN instance
# (Make sure to add the plugins to CKAN__PLUGINS in the .env file)
# TODO: pin when possible
RUN echo 'Installing extensions' && \
    # scheming
    pip install -e git+https://github.com/ckan/ckanext-scheming.git#egg=ckanext-scheming && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-scheming/master/requirements.txt && \
    # harvest
    pip install -e git+https://github.com/ckan/ckanext-harvest.git@v1.1.4#egg=ckanext-harvest && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-harvest/v1.1.4/pip-requirements.txt && \
    # googleanalytics
    pip install -e git+https://github.com/zelima/ckanext-googleanalytics.git#egg=ckanext-googleanalytics && \
    pip install -r https://raw.githubusercontent.com/zelima/ckanext-googleanalytics/master/requirements.txt && \
    # GA-report
    pip install -e git+https://github.com/CivicActions/ckanext-ga-report.git@v0.0.1#egg=ckanext-ga-report && \
    pip install -r https://raw.githubusercontent.com/CivicActions/ckanext-ga-report/master/requirements.txt && \
    # showcase
    pip install -e git+https://github.com/keitaroinc/ckanext-showcase.git@ckan-2.8#egg=ckanext-showcase && \
    # pages
    pip install -e git+https://github.com/keitaroinc/ckanext-pages.git@pages-ckan-2.8#egg=ckanext-pages && \
    # disqus
    pip install -e git+https://github.com/ckan/ckanext-disqus#egg=ckanext-disqus && \
    # datajson
    pip install -e git+https://github.com/okfn/ckanext-datajson.git@ed#egg=ckanext-datajson && \
    pip install -r ${APP_DIR}/src/ckanext-datajson/requirements.txt && \
    # hierarchy
    pip install -e git+https://github.com/okfn/ckanext-hierarchy.git#egg=ckanext-hierarchy && \
    # geoview
    pip install -e git+https://github.com/okfn/ckanext-geoview.git@#egg=ckanext-geoview && \
    # pdfview
    pip install -e git+https://github.com/okfn/ckanext-pdfview.git#egg=ckanext-pdfview  && \
    # contact
    pip install -e git+https://github.com/okfn/ckanext-contact.git@lacounts-0.1#egg=ckanext-contact

# Install project extension
RUN pip install -e git+https://github.com/CivicActions/ckanext-ed.git#egg=ckanext-ed

# Apply patches
COPY patches ${APP_DIR}/patches

RUN for d in $APP_DIR/patches/*; do \
        for f in `ls $d/*.patch | sort -g`; do \
		    cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
        done ; \
    done

# Copy config files
COPY crontabs/* /etc/crontabs/
COPY docker-entrypoint.d/* /docker-entrypoint.d/
COPY supervisor.d/* /etc/supervisord.d/
COPY token.dat $APP_DIR/token.dat
COPY credentials.json $APP_DIR/credentials.json
